name: couteaouapp
description: "new app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.4
  provider: ^6.0.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/toolbox.png
    - assets/images/home.png
    - assets/images/person.png
    - assets/images/cake.png
    - assets/images/school.png
    - assets/images/cloud.png
    - assets/images/pokemon.png
    - assets/images/article.png
    - assets/images/info.png
    - assets/images/young.jpg
    - assets/images/adult.jpg
    - assets/images/elderly.jpg
    - assets/images/icon.png
    - assets/images/background.jpg
    - assets/images/center.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/perfil.jpg"